# This file is at the root level, as it applies to all Python code,
# not only to docs or to tools.
[tool.pyright]
extends = "bazel-bin/examples/simple/ide_support.runfiles/score_python_basics~/pyproject.toml"

exclude = [
    "**/__pycache__",
    "**/.*",
    "**/bazel-*",
    "venv/**",
]

[tool.ruff]
extend = "bazel-bin/examples/simple/ide_support.runfiles/score_python_basics~/pyproject.toml"

extend-exclude = [
    "**/__pycache__",
    "/.*",
    "bazel-*",
    "venv/**",
]
