# *******************************************************************************
# Copyright (c) 2026 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

# ╓                                                          ╖
# ║ Some portions generated by Github Copilot                ║
# ╙                                                          ╜

"""Shared helpers for score_harness utilities."""

from __future__ import annotations

import importlib.util
import json
from pathlib import Path


def load_harness(candidate_path: Path):
    """Dynamically load a harness candidate from a Python file."""
    spec = importlib.util.spec_from_file_location("candidate_harness", candidate_path)
    if spec is None or spec.loader is None:
        raise ValueError(f"Cannot load module spec from {candidate_path}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    for name in dir(module):
        cls = getattr(module, name)
        try:
            if (
                isinstance(cls, type)
                and name != "AssuranceHarness"
                and issubclass(cls, module.AssuranceHarness)
            ):
                return cls()
        except (TypeError, AttributeError):
            continue
    raise ValueError(f"No AssuranceHarness subclass found in {candidate_path}")


def load_task_specs(tasks_dir: Path) -> list[dict]:
    """Load all task spec JSON files from the tasks directory."""
    specs = []
    for path in sorted(tasks_dir.glob("*.json")):
        spec = json.loads(path.read_text())
        spec["_task_spec_path"] = str(path.resolve())
        specs.append(spec)
    return specs
