# *******************************************************************************
# Copyright (c) 2026 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************
"""# *******************************************************************************
# Copyright (c) 2026 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

# ╓                                                          ╖
# ║ Some portions generated by Github Copilot                ║
# ╙                                                          ╜
Outer loop for the docs-as-code assurance harness.

This script is deterministic Python — no LLM required.
It loads a harness candidate, runs it against a task set, calls the Lane A gate,
distills structured trace artifacts, and appends a summary line to
evolution_summary.jsonl.

Usage:
    python3 outer_loop.py --candidate harness/base_harness.py --tasks spec/ \
        [--iteration 1] [--output-dir runs/]
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import subprocess
import sys
from datetime import UTC, datetime
from pathlib import Path

from common import load_harness, load_task_specs
from validate_candidate import validate_candidate


def run_gate_from_needs_json(
    needs_json: Path,
    gate_script: Path,
    gate_args: list[str],
) -> dict:
    """
    Run traceability_gate.py using metrics.json from the same build as needs.json.

    In this repo, the docs build (Sphinx + score_metamodel extension) produces
    both needs.json and metrics.json. The gate validates the metrics.json.

    This function locates metrics.json in the same directory as needs.json.
    """
    # Locate metrics.json alongside needs.json
    metrics_json = needs_json.parent / "metrics.json"
    if not metrics_json.exists():
        return {
            "metrics": {"error": f"metrics.json not found at {metrics_json}"},
            "gate_passed": False,
            "gate_stdout": f"Error: metrics.json not found at {metrics_json}",
            "gate_returncode": 1,
        }

    metrics = json.loads(metrics_json.read_text())
    gate_result = subprocess.run(
        [sys.executable, str(gate_script), "--metrics-json", str(metrics_json)]
        + gate_args,
        capture_output=True,
        text=True,
    )

    return {
        "metrics": metrics,
        "gate_passed": gate_result.returncode == 0,
        "gate_stdout": gate_result.stdout,
        "gate_returncode": gate_result.returncode,
    }


def run_gate_from_metrics_json(
    metrics_json: Path,
    gate_script: Path,
    gate_args: list[str],
) -> dict:
    """
    Run traceability_gate.py directly on an existing metrics.json fixture.
    This mode is useful for task specs derived from gate tests and fixtures.
    """
    metrics = json.loads(metrics_json.read_text())
    gate_result = subprocess.run(
        [sys.executable, str(gate_script), "--metrics-json", str(metrics_json)]
        + gate_args,
        capture_output=True,
        text=True,
    )

    return {
        "metrics": metrics,
        "gate_passed": gate_result.returncode == 0,
        "gate_stdout": gate_result.stdout,
        "gate_returncode": gate_result.returncode,
    }


def distill_trace(gate_result: dict, task_spec: dict) -> dict:
    """
    Extract only the fields the proposer needs. Never raw stdout dumps.
    This is the distillation step — deterministic, no LLM.
    """
    metrics = gate_result.get("metrics", {})
    impacted = []

    # Extract broken complies/test references by type from metrics
    for req_type, data in metrics.get("metrics_by_type", {}).items():
        reqs = data.get("requirements", {})
        if reqs.get("with_test_link_pct", 100) < 100:
            impacted.append(
                {
                    "artifact_type": req_type,
                    "impact_class": "direct_recheck",
                    "reason": "missing_test_link",
                }
            )
        if reqs.get("with_code_link_pct", 100) < 100:
            impacted.append(
                {
                    "artifact_type": req_type,
                    "impact_class": "direct_recheck",
                    "reason": "missing_code_link",
                }
            )
        tests = data.get("tests", {})
        broken_references = tests.get("broken_references", [])
        if isinstance(broken_references, int):
            broken_reference_count = broken_references
        else:
            broken_reference_count = len(broken_references)
        if broken_reference_count > 0:
            impacted.append(
                {
                    "artifact_type": req_type,
                    "impact_class": "revision_required",
                    "reason": "broken_test_reference",
                    "count": broken_reference_count,
                    "references": broken_references,
                }
            )

    return {
        "gate_passed": gate_result["gate_passed"],
        "expected_verdict": task_spec.get("expected_verdict", "unknown"),
        "task_mode": "metrics_json"
        if task_spec.get("metrics_json_path")
        else "needs_json",
        "verdict_correct": gate_result["gate_passed"]
        == (task_spec.get("expected_verdict") == "pass"),
        "impacted_elements": impacted,
        "coverage_summary": metrics.get("metrics_by_type", {}),
        "responsible_role": task_spec.get("responsible_role", "pr_creator"),
        "provenance": {
            "execution_timestamp": datetime.now(UTC).isoformat(),
            "python_version": sys.version.split()[0],
            "environment_hash": hashlib.sha256(
                f"{sys.version}{os.environ.get('USER', 'unknown')}".encode()
            ).hexdigest()[:16],
            "gate_script_version": "1.0",
        },
    }


def resolve_task_path(path_value: str, task_spec: dict) -> Path:
    """Resolve a task artifact path robustly across common invocation directories."""
    path = Path(path_value)
    if path.is_absolute():
        return path

    candidates = [Path.cwd() / path]
    task_spec_path = Path(task_spec.get("_task_spec_path", ""))
    if task_spec_path:
        task_dir = task_spec_path.parent
        harness_root = task_dir.parent
        candidates.extend(
            [
                task_dir / path,
                harness_root / path,
            ]
        )
        if path.parts and path.parts[0] == harness_root.name:
            candidates.append(harness_root.parent / path)

    for candidate in candidates:
        if candidate.exists():
            return candidate

    return candidates[0]


def resolve_support_path(path_value: Path) -> Path:
    """Resolve repo support scripts independent of the current working directory."""
    if path_value.is_absolute():
        return path_value

    repo_root = Path(__file__).resolve().parent.parent
    candidates = [Path.cwd() / path_value, repo_root / path_value]
    for candidate in candidates:
        if candidate.exists():
            return candidate
    return repo_root / path_value


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


def main() -> None:  # noqa: C901
    parser = argparse.ArgumentParser(description="Score harness outer loop")
    parser.add_argument("--candidate", required=True, type=Path)
    parser.add_argument("--tasks", required=True, type=Path)
    parser.add_argument("--iteration", type=int, default=1)
    parser.add_argument("--output-dir", type=Path, default=Path("runs"))
    parser.add_argument(
        "--gate-script",
        type=Path,
        default=Path("scripts_bazel/traceability_gate.py"),
    )
    parser.add_argument(
        "--skip-validation",
        action="store_true",
        help="Skip the cheap pre-benchmark candidate validation step.",
    )
    args = parser.parse_args()
    args.gate_script = resolve_support_path(args.gate_script)

    candidate_name = args.candidate.stem
    run_dir = args.output_dir / f"iteration_{args.iteration:03d}" / candidate_name
    run_dir.mkdir(parents=True, exist_ok=True)

    harness = load_harness(args.candidate)
    task_specs = load_task_specs(args.tasks)

    if not task_specs:
        print(f"No task specs found in {args.tasks}. Create spec/*.json files first.")
        sys.exit(1)

    if not args.skip_validation:
        validation_task_spec = None
        for candidate_task_spec in sorted(args.tasks.glob("*.json")):
            task_data = json.loads(candidate_task_spec.read_text())
            if not task_data.get("active", True):
                continue
            if task_data.get("needs_json_path") or task_data.get("metrics_json_path"):
                validation_task_spec = candidate_task_spec
                break

        if validation_task_spec is None:
            print("No runnable task spec found for validation.")
            sys.exit(1)

        validation_result = validate_candidate(
            args.candidate,
            validation_task_spec,
            skip_external_checks=False,
        )

        # Log validation failures for learning
        if validation_result["status"] == "failed":
            from score_harness.validate_candidate import log_validation_failure

            log_validation_failure(
                args.iteration,
                validation_result["candidate"],
                validation_result["failures"],
            )
            print(
                f"[validation] FAILED: {validation_result['candidate']} "
                f"— {len(validation_result['failures'])} failures logged to validation_failures.jsonl"
            )
            for failure in validation_result["failures"]:
                print(f"  - {failure['failure_type']}: {failure['fix']}")
            sys.exit(1)

        print(
            f"[validation] candidate={validation_result['candidate']} "
            f"task={validation_result['task_id']} status={validation_result['status']}"
        )

    task_results = []
    for task_spec in task_specs:
        if not task_spec.get("active", True):
            print(f"  [SKIP] {task_spec.get('id', 'unknown')}: inactive task spec")
            continue

        task_id = task_spec.get("id", "unknown")
        trace_dir = run_dir / "traces" / task_id
        trace_dir.mkdir(parents=True, exist_ok=True)

        # Get harness context (would be passed to agent in a real run)
        harness.get_context(task_spec)

        gate_args = task_spec.get("gate_args", [])

        metrics_json_path = task_spec.get("metrics_json_path", "")
        if metrics_json_path:
            metrics_json = resolve_task_path(metrics_json_path, task_spec)
            if not metrics_json.exists():
                print(f"  [SKIP] {task_id}: metrics_json not found at {metrics_json}")
                continue
            gate_result = run_gate_from_metrics_json(
                metrics_json,
                args.gate_script,
                gate_args,
            )
        else:
            needs_json_path = task_spec.get("needs_json_path", "")
            if not needs_json_path:
                print(f"  [SKIP] {task_id}: no needs_json_path provided")
                continue
            needs_json = resolve_task_path(needs_json_path, task_spec)
            if not needs_json.exists():
                print(f"  [SKIP] {task_id}: needs_json not found at {needs_json}")
                continue

            gate_result = run_gate_from_needs_json(
                needs_json,
                args.gate_script,
                gate_args,
            )
        trace = distill_trace(gate_result, task_spec)

        # Write distilled trace files
        (trace_dir / "gate_output.json").write_text(
            json.dumps(
                {
                    "gate_passed": gate_result["gate_passed"],
                    "gate_returncode": gate_result["gate_returncode"],
                },
                indent=2,
            )
        )
        (trace_dir / "impacted_elements.json").write_text(
            json.dumps(trace["impacted_elements"], indent=2)
        )
        (trace_dir / "score.json").write_text(json.dumps(trace, indent=2))

        task_results.append(
            {
                "task_id": task_id,
                "verdict_correct": trace["verdict_correct"],
                "gate_passed": trace["gate_passed"],
                "task_mode": trace["task_mode"],
            }
        )
        print(f"  [{'+' if trace['verdict_correct'] else 'X'}] {task_id}")

    # Write run-level score
    n_correct = sum(1 for r in task_results if r["verdict_correct"])
    (run_dir / "score.json").write_text(
        json.dumps(
            {
                "candidate": candidate_name,
                "iteration": args.iteration,
                "tasks_total": len(task_results),
                "tasks_correct": n_correct,
                "pass_rate": n_correct / len(task_results) if task_results else 0.0,
                "timestamp": datetime.now(UTC).isoformat(),
            },
            indent=2,
        )
    )

    # Append to evolution_summary.jsonl
    summary_path = args.output_dir / "evolution_summary.jsonl"
    with summary_path.open("a") as f:
        f.write(
            json.dumps(
                {
                    "iteration": args.iteration,
                    "candidate": candidate_name,
                    "pass_rate": n_correct / len(task_results) if task_results else 0.0,
                    "tasks_total": len(task_results),
                    "timestamp": datetime.now(UTC).isoformat(),
                }
            )
            + "\n"
        )

    print(f"\n{candidate_name}: {n_correct}/{len(task_results)} correct")
    print(f"Traces written to {run_dir}")
    print(f"Summary appended to {summary_path}")


if __name__ == "__main__":
    main()
