# *******************************************************************************
# Copyright (c) 2026 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************
"""# *******************************************************************************
# Copyright (c) 2026 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

# ╓                                                          ╖
# ║ Some portions generated by Github Copilot                ║
# ╙                                                          ╜
Small helper for querying score_harness run history.

This helper keeps navigation cheap for both humans and agents by exposing a
small summary interface over the append-only runs/ filesystem.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path


def read_summary(summary_path: Path) -> list[dict]:
    if not summary_path.exists():
        return []
    rows = []
    for line in summary_path.read_text().splitlines():
        if not line.strip():
            continue
        rows.append(json.loads(line))
    return rows


def print_top_candidates(rows: list[dict], top_k: int) -> None:
    ranked = sorted(rows, key=lambda row: row.get("pass_rate", 0.0), reverse=True)
    for row in ranked[:top_k]:
        print(
            f"iteration={row.get('iteration')} candidate={row.get('candidate')} "
            f"pass_rate={row.get('pass_rate', 0.0):.3f} tasks={row.get('tasks_total', 0)}"
        )


def print_failed_tasks(runs_dir: Path, candidate: str | None = None) -> None:
    candidate_dirs = sorted(runs_dir.glob("iteration_*/**/traces/*/score.json"))
    for score_path in candidate_dirs:
        candidate_name = score_path.parents[2].name
        if candidate and candidate_name != candidate:
            continue
        score = json.loads(score_path.read_text())
        if not score.get("verdict_correct", False):
            task_id = score_path.parent.name
            print(
                f"candidate={candidate_name} task={task_id} "
                f"gate_passed={score.get('gate_passed')} "
                f"expected={score.get('expected_verdict')}"
            )


def load_task_scores(runs_dir: Path, candidate: str) -> dict[str, dict]:
    scores: dict[str, dict] = {}
    for score_path in sorted(
        runs_dir.glob(f"iteration_*/{candidate}/traces/*/score.json")
    ):
        scores[score_path.parent.name] = json.loads(score_path.read_text())
    return scores


def print_candidate_diff(runs_dir: Path, left: str, right: str) -> None:
    left_scores = load_task_scores(runs_dir, left)
    right_scores = load_task_scores(runs_dir, right)
    task_ids = sorted(set(left_scores) | set(right_scores))

    for task_id in task_ids:
        left_score = left_scores.get(task_id)
        right_score = right_scores.get(task_id)
        if left_score is None or right_score is None:
            print(
                f"task={task_id} present_in={left if left_score else ''}"
                f"{right if right_score else ''}"
            )
            continue

        if left_score.get("verdict_correct") != right_score.get("verdict_correct"):
            print(
                f"task={task_id} {left}={left_score.get('verdict_correct')} "
                f"{right}={right_score.get('verdict_correct')}"
            )


def main() -> None:
    parser = argparse.ArgumentParser(description="Query score-harness run history")
    parser.add_argument("--runs-dir", type=Path, default=Path("runs"))
    parser.add_argument("--top", type=int, default=5)
    parser.add_argument("--failed-tasks", action="store_true")
    parser.add_argument("--candidate", type=str)
    parser.add_argument("--diff-candidates", nargs=2, metavar=("LEFT", "RIGHT"))
    args = parser.parse_args()

    rows = read_summary(args.runs_dir / "evolution_summary.jsonl")
    if rows:
        print("Top candidates")
        print("--------------")
        print_top_candidates(rows, args.top)
    else:
        print("No run summary found yet.")

    if args.failed_tasks:
        print()
        print("Failed tasks")
        print("------------")
        print_failed_tasks(args.runs_dir, args.candidate)

    if args.diff_candidates:
        left, right = args.diff_candidates
        print()
        print("Candidate diff")
        print("--------------")
        print_candidate_diff(args.runs_dir, left, right)


if __name__ == "__main__":
    main()
