# *******************************************************************************
# Copyright (c) 2026 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************
"""# *******************************************************************************
# Copyright (c) 2026 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

# ╓                                                          ╖
# ║ Some portions generated by Github Copilot                ║
# ╙                                                          ╜
Lightweight validation for docs-as-code harness candidates.

This is the cheap pre-benchmark check. It catches malformed candidates before
they consume the full task set or expensive gate runs.

Validation covers:
1. candidate module loads
2. candidate class instantiates
3. get_context() returns a string for one tiny task spec
4. post_process() returns a dict
5. expected trace filenames are known and stable
6. task spec provides either needs_json_path or metrics_json_path
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

from score_harness.common import load_harness

REQUIRED_TRACE_FILENAMES = (
    "gate_output.json",
    "impacted_elements.json",
    "score.json",
)


def validate_candidate(candidate_path: Path, task_spec_path: Path) -> dict:
    """Return a structured validation result for one candidate and one tiny task."""
    harness = load_harness(candidate_path)
    task_spec = json.loads(task_spec_path.read_text())
    if not task_spec.get("active", True):
        raise ValueError("task spec is inactive; choose a runnable task spec")

    if not task_spec.get("needs_json_path") and not task_spec.get("metrics_json_path"):
        raise ValueError(
            "task spec must provide either needs_json_path or metrics_json_path"
        )

    context = harness.get_context(task_spec)
    if not isinstance(context, str):
        raise TypeError(f"get_context() must return str, got {type(context).__name__}")

    post_processed = harness.post_process("", task_spec)
    if not isinstance(post_processed, dict):
        raise TypeError(
            f"post_process() must return dict, got {type(post_processed).__name__}"
        )

    return {
        "candidate": candidate_path.stem,
        "task_id": task_spec.get("id", "unknown"),
        "context_length": len(context),
        "required_trace_filenames": list(REQUIRED_TRACE_FILENAMES),
        "status": "ok",
    }


def main() -> None:
    parser = argparse.ArgumentParser(description="Validate a score-harness candidate")
    parser.add_argument("--candidate", required=True, type=Path)
    parser.add_argument("--task-spec", required=True, type=Path)
    args = parser.parse_args()

    result = validate_candidate(args.candidate, args.task_spec)
    print(json.dumps(result, indent=2))


if __name__ == "__main__":
    main()
