# *******************************************************************************
# Copyright (c) 2026 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

# ╓                                                          ╖
# ║ Some portions generated by Github Copilot                ║
# ╙                                                          ╜

"""Needpie filter functions backed by shared traceability metric calculations."""

from __future__ import annotations

from sphinx_needs.need_item import NeedItem

from ..traceability_metrics import compute_traceability_summary, filter_requirements


def _requirement_types(kwargs: dict[str, str | int | float]) -> set[str]:
    raw = str(kwargs.get("arg1", "tool_req")).strip()
    values = {value.strip() for value in raw.split(",") if value.strip()}
    return values or {"tool_req"}


def pie_requirements_status(
    needs: list[NeedItem], results: list[int], **kwargs: str | int | float
) -> None:
    """Dashboard status split: not implemented, implemented/incomplete, fully linked."""
    req_types = _requirement_types(kwargs)

    all_requirements = filter_requirements(
        needs,
        requirement_types=req_types,
        include_not_implemented=True,
    )
    implemented_requirements = filter_requirements(
        needs,
        requirement_types=req_types,
        include_not_implemented=False,
    )
    summary = compute_traceability_summary(
        all_needs=needs,
        requirement_types=req_types,
        include_not_implemented=False,
        filtered_test_types=set(),
    )

    not_implemented = len(all_requirements) - len(implemented_requirements)
    fully_linked = int(summary["requirements"]["fully_linked"])
    implemented_incomplete = len(implemented_requirements) - fully_linked

    results.append(not_implemented)
    results.append(implemented_incomplete)
    results.append(fully_linked)


def pie_requirements_with_code_links(
    needs: list[NeedItem], results: list[int], **kwargs: str | int | float
) -> None:
    """Dashboard split: requirements with and without source code links."""
    req_types = _requirement_types(kwargs)
    summary = compute_traceability_summary(
        all_needs=needs,
        requirement_types=req_types,
        include_not_implemented=True,
        filtered_test_types=set(),
    )

    total = int(summary["requirements"]["total"])
    with_code = int(summary["requirements"]["with_code_link"])

    results.append(total - with_code)
    results.append(with_code)
