#load("@dependix_pytest//:defs.bzl", "py_pytest")
#load("@pip//:requirements.bzl", "requirement")

# py_pytest(
#     name = "test_xml_parse_and_writing",
#     size = "small",
#     srcs = [
#         "test_xml_parsing.py",
#     ],
#     args = ["--basetemp /tmp/pytest"],
#     imports = ["."],
#     visibility = [
#         "//visibility:public",
#     ],
#     deps = ["//tools/sphinx_extensions/build/test_xml_parser:docs_with_testing_info"],
# )
