# *******************************************************************************
# Copyright (c) 2026 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************
"""# *******************************************************************************
# Copyright (c) 2026 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

# ╓                                                          ╖
# ║ Some portions generated by Github Copilot                ║
# ╙                                                          ╜
Base harness interface for the docs-as-code assurance consistency domain.

Every candidate harness must subclass AssuranceHarness and override get_context().
The outer loop loads and evaluates candidates via this interface without modification.
"""

from __future__ import annotations

from abc import ABC, abstractmethod


class AssuranceHarness(ABC):
    """
    Interface every candidate harness must satisfy.

    The outer loop calls get_context() before the agent acts, then runs the
    Lane A gate, then calls post_process() on the result before distillation.
    """

    @abstractmethod
    def get_context(self, task_spec: dict) -> str:
        """
        Return context to present to the agent before it acts on the task.

        task_spec fields (from spec.md parsed as dict):
          - input_path: str        path to the RST or needs.json file to change
          - change_description: str what the agent should do
          - expected_verdict: str  "pass" or "fail" (used only for evaluation)
          - consistency_rules: list[str]  rule IDs expected to be relevant

        Returns a string that will be prepended to the agent's task prompt.
        """
        ...

    def post_process(self, agent_output: str, task_spec: dict) -> dict:
        """
        Optional: transform or validate agent output before the gate runs.

        Default implementation returns the output unchanged.
        Override to add pre-gate validation, output normalization, etc.
        """
        return {"agent_output": agent_output}


class BaselineHarness(AssuranceHarness):
    """
    Baseline: no pre-context. Agent receives only the task description.

    This is the weakest possible harness and serves as the search baseline.
    Any candidate that beats this on the search set is a candidate improvement.
    """

    def get_context(self, task_spec: dict) -> str:
        return ""
