# *******************************************************************************
# Copyright (c) 2026 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************
"""# *******************************************************************************
# Copyright (c) 2026 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

# ╓                                                          ╖
# ║ Some portions generated by Github Copilot                ║
# ╙                                                          ╜
Rule-retrieval harness: provides consistency rule context for each task.

This candidate reads the consistency_rules field from the task spec, retrieves
the corresponding rule definitions from consistency_rules.yaml, and formats
them as context prepended to the agent's task prompt.

Hypothesis: explicit consistency rule context reduces false-negative gate
failures by helping the agent preserve coverage invariants.
"""

from __future__ import annotations

import sys
from pathlib import Path

import yaml

# Inject harness directory into path so base_harness can be imported
_harness_dir = Path(__file__).parent
if str(_harness_dir) not in sys.path:
    sys.path.insert(0, str(_harness_dir))

from base_harness import AssuranceHarness  # noqa: E402


class RuleRetrievalHarness(AssuranceHarness):
    """
    Harness that retrieves and formats consistency rules for the agent.

    For each rule ID in task_spec["consistency_rules"], this candidate:
    1. Loads the rule definition from consistency_rules.yaml
    2. Formats the trigger, impact class, and required action
    3. Returns the formatted rules as context
    """

    def __init__(self):
        self.rules_cache = None

    def _load_rules(self) -> dict[str, dict]:
        """Load and index the consistency rule catalog."""
        if self.rules_cache is not None:
            return self.rules_cache

        # Resolve rules file relative to this harness file
        harness_dir = Path(__file__).parent
        rules_path = harness_dir.parent / "consistency_rules.yaml"

        if not rules_path.exists():
            return {}

        with rules_path.open() as f:
            data = yaml.safe_load(f)

        rules_by_id = {rule["id"]: rule for rule in data.get("rules", [])}
        self.rules_cache = rules_by_id
        return rules_by_id

    def get_context(self, task_spec: dict) -> str:
        """
        Retrieve and format consistency rules referenced in the task spec.

        Returns a formatted string listing each rule's trigger, impact class,
        and required action, designed to be prepended to the agent's prompt.
        """
        rule_ids = task_spec.get("consistency_rules", [])
        if not rule_ids:
            return ""

        rules_by_id = self._load_rules()
        context_lines = ["## Relevant Consistency Rules", ""]

        for rule_id in rule_ids:
            rule = rules_by_id.get(rule_id)
            if not rule:
                context_lines.append(f"- {rule_id}: (rule not found)")
                continue

            context_lines.append(
                f"### {rule_id}: {rule.get('description', '').strip()}"
            )
            context_lines.append("")

            trigger = rule.get("trigger", {})
            context_lines.append(
                f"**Trigger**: {trigger.get('artifact_type', 'unknown')} — {trigger.get('change', 'unknown')}"
            )
            context_lines.append(
                f"**Impact class**: {rule.get('impact_class', 'unknown')}"
            )
            context_lines.append(
                f"**Action required**: {rule.get('action_required', 'unknown')}"
            )
            context_lines.append("")

        return "\n".join(context_lines)
