# *******************************************************************************
# Copyright (c) 2026 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

"""Load the mounts manifest JSON emitted by the ``_mounts_manifest`` Bazel rule.

All mount paths are authored by Bazel (where ``File`` objects have real paths)
and shipped in a small JSON manifest. This module only *reads* that manifest — it
performs no label-to-path reconstruction. Every path stored in the manifest is a
Bazel ``short_path`` and therefore resolves relative to the manifest's own
directory."""

from __future__ import annotations

import json
import os
from dataclasses import dataclass
from pathlib import Path


@dataclass(frozen=True)
class MountSpec:
    src_root: str
    runtime_path: str
    mount_at: str
    attach_to: str | None = None
    entry_doc: str = "index"
    external: bool = False


@dataclass(frozen=True)
class MountsManifest:
    manifest_path: Path
    mounts: list[MountSpec]

    @property
    def root(self) -> Path:
        """Directory the manifest lives in — the base for its short_path entries."""
        return self.manifest_path.parent

    def runtime_dir(self, spec: MountSpec) -> Path:
        """Absolute path of a bundle's staged mount-root directory.

        ``runtime_path`` is a Bazel ``short_path`` (the bundle's source
        directory, staged in place — not a copy) and resolves relative to the
        manifest's own directory. Main-repo sources resolve the same way inside a
        sandbox build. External sources (``../<repo>+/X``) are only ever walked
        under ``bazel run`` with an external bundle, where ``../`` steps out
        of ``_main`` to the sibling repo dir in the runfiles tree — so no
        context-dependent mapping is needed here.
        """
        base = self.root.parent if spec.external else self.root
        return _resolve_below(base, spec.runtime_path)


def _validate_relative_path(value: object, field_name: str, *, external: bool) -> str:
    """Apply a defense-in-depth check before a manifest path reaches the filesystem.

    Internal paths are relative to the manifest directory. External runfiles use
    Bazel's ``../<repository>/...`` spelling and are relative to its parent.

    This is intentionally not part of the normal bundle semantics: Bazel's
    Starlark rules already produce paths in this format. The validation only
    protects direct or tampered manifest input from turning into filesystem
    traversal when this Python extension reads it.
    """
    if not isinstance(value, str) or not value:
        raise ValueError(f"{field_name} must be a non-empty string")

    parts = value.split("/")
    if external:
        if len(parts) < 3 or parts[0] != "..":
            raise ValueError(
                f"external {field_name} must start with '../<repository>/': {value!r}"
            )
        parts = parts[1:]
    if any(not part or part in {".", ".."} for part in parts):
        raise ValueError(
            f"{field_name} must not contain empty, '.' or '..' segments: {value!r}"
        )
    return value


def _resolve_below(base: Path, relative_path: str) -> Path:
    """Keep a validated path inside its Bazel-controlled root (security boundary)."""
    # Keep this as ``os.path.normpath`` plus ``startswith`` instead of the
    # equivalent pathlib operations: CodeQL models this pair as a normalized,
    # root-confined path for its path-injection analysis.
    resolved_base = os.path.normpath(os.path.abspath(base))
    # External runtime paths begin with '../' but are resolved against the
    # manifest's parent, so their repository directory remains below this base.
    relative = relative_path.removeprefix("../")
    # Do not resolve symlinks here: test runfiles and Bazel workspaces commonly
    # expose in-tree sources through symlinks. The manifest validation above
    # rejects traversal segments, while ``abspath`` normalizes the lexical path.
    resolved_path = os.path.normpath(os.path.join(resolved_base, relative))
    if not resolved_path.startswith(resolved_base + os.sep):
        raise ValueError(f"mount path escapes its expected root: {relative_path!r}")
    return Path(resolved_path)


def load_mounts_manifest(manifest_path: str | Path) -> MountsManifest:
    """Read the manifest JSON at ``manifest_path`` (an already-resolved path).

    Context-dependent path resolution (runfiles under ``bazel run`` vs. the
    exec root in a sandbox) is the caller's responsibility. The manifest is
    normally generated by Bazel, so its schema checks below are deliberately
    defense-in-depth rather than a functional requirement for bundle loading.
    """
    manifest_path = Path(manifest_path)
    data = json.loads(manifest_path.read_text(encoding="utf-8"))
    if not isinstance(data, dict):
        raise ValueError(
            f"mounts manifest must be a JSON object, got {type(data).__name__}: {data!r}"
        )
    mounts: list[MountSpec] = []
    for entry in data.get("mounts", []):
        if (
            not isinstance(entry, dict)
            or "src_root" not in entry
            or "mount_at" not in entry
        ):
            raise ValueError(
                f"mounts manifest entry missing 'src_root'/'mount_at': {entry!r}"
            )
        external = entry.get("external", False)
        if not isinstance(external, bool):
            raise ValueError(f"mounts manifest 'external' must be boolean: {entry!r}")
        mounts.append(
            MountSpec(
                src_root=_validate_relative_path(
                    entry["src_root"], "src_root", external=False
                ),
                runtime_path=_validate_relative_path(
                    entry.get("runtime_path", ""), "runtime_path", external=external
                ),
                mount_at=entry["mount_at"],
                attach_to=entry.get("attach_to") or None,
                entry_doc=entry.get("entry_doc") or "index",
                external=external,
            )
        )
    return MountsManifest(
        manifest_path=manifest_path,
        mounts=mounts,
    )


def resolve_walk_dir(
    manifest: MountsManifest, spec: MountSpec, ws_root: Path | None
) -> Path:
    """Resolve a mount directory for either ``bazel run`` or a sandbox build."""
    if spec.external and ws_root is not None:
        return manifest.runtime_dir(spec)
    if ws_root is not None:
        return _resolve_below(ws_root, spec.src_root)
    return _resolve_below(Path.cwd(), spec.src_root)
