# *******************************************************************************
# Copyright (c) 2026 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

# ╓                                                          ╖
# ║ Some portions generated by Github Copilot                ║
# ╙                                                          ╜

"""Tests for harness common utilities."""

from __future__ import annotations

from pathlib import Path

# Import from workspace target
import score_harness.common as common_module

_MY_PATH = Path(__file__).parent


def test_load_harness_baseline():
    """Test loading baseline harness."""
    harness_path = _MY_PATH.parent / "harness" / "base_harness.py"
    harness_cls = common_module.load_harness(harness_path)

    assert harness_cls is not None
    assert hasattr(harness_cls, "get_context")
    assert hasattr(harness_cls, "post_process")


def test_load_task_specs():
    """Test loading task specs from spec directory."""
    spec_dir = _MY_PATH.parent / "spec"
    tasks = common_module.load_task_specs(spec_dir)

    assert len(tasks) > 0, "Should have at least one task spec"

    for task in tasks:
        # Task specs use "id" not "task_id"
        assert "id" in task
        assert "_task_spec_path" in task
        assert Path(task["_task_spec_path"]).exists()
