# *******************************************************************************
# Copyright (c) 2026 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

# ╓                                                          ╖
# ║ Some portions generated by Github Copilot                ║
# ╙                                                          ╜

"""Tests for validate_candidate.py"""

from __future__ import annotations

from pathlib import Path

# Import from workspace target
import score_harness.validate_candidate as validate_candidate_module

_MY_PATH = Path(__file__).parent


def test_validate_harness_baseline():
    """Test that baseline harness passes validation."""

    harness_path = _MY_PATH.parent / "harness" / "base_harness.py"
    assert harness_path.exists(), f"Harness not found: {harness_path}"

    # Use a minimal task spec for validation
    task_spec_path = _MY_PATH.parent / "spec" / "task_002_threshold_fail.json"
    assert task_spec_path.exists(), f"Task spec not found: {task_spec_path}"

    # Should not raise
    result = validate_candidate_module.validate_candidate(harness_path, task_spec_path)
    assert isinstance(result, dict)
    assert result.get("status") == "ok"
    assert "context_length" in result


def test_validate_harness_rule_retrieval():
    """Test that rule_retrieval harness passes validation."""
    harness_path = _MY_PATH.parent / "harness" / "rule_retrieval_harness.py"
    assert harness_path.exists(), f"Harness not found: {harness_path}"

    # Use a minimal task spec for validation
    task_spec_path = _MY_PATH.parent / "spec" / "task_002_threshold_fail.json"
    assert task_spec_path.exists(), f"Task spec not found: {task_spec_path}"

    # Should not raise
    result = validate_candidate_module.validate_candidate(harness_path, task_spec_path)
    assert isinstance(result, dict)
    assert result.get("status") == "ok"
    assert "context_length" in result


def test_task_spec_schema():
    """Test that task specs have required fields."""
    import json

    spec_dir = _MY_PATH.parent / "spec"

    for spec_file in spec_dir.glob("task_*.json"):
        with open(spec_file) as f:
            spec = json.load(f)

        # Skip inactive examples
        if spec.get("active") is False:
            continue

        # Check required fields
        assert "id" in spec, f"{spec_file.name}: missing id"
        assert "description" in spec, f"{spec_file.name}: missing description"
        assert "responsible_role" in spec, f"{spec_file.name}: missing responsible_role"

        # Check that task has either metrics_json_path or needs_json_path
        has_metrics = "metrics_json_path" in spec
        has_needs = "needs_json_path" in spec
        assert has_metrics or has_needs, (
            f"{spec_file.name}: must have metrics_json_path or needs_json_path"
        )
