# *******************************************************************************
# Copyright (c) 2026 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************
name: On Pull Request

on:
  pull_request:
    types: [opened, reopened, synchronize]
  merge_group:
    types: [checks_requested]

permissions:
  contents: read
  id-token: write

jobs:
  on-pr:
    # FIXME: change to @main once the workflow is merged into main
    uses: eclipse-score/cicd-workflows/.github/workflows/on-pr.yml@on-pr
