# *******************************************************************************
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

name: Run renovate

on:
  schedule:
    - cron: "0 19 * * *" # Every day at 9:00 PM Europe time
  workflow_dispatch: {} # Allow manual runs too

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Run renovate
        uses: renovatebot/github-action@v42.0.2
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
