# *******************************************************************************
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

name: Run Bazel Tests
on:
  pull_request:
    types: [opened, reopened, synchronize]
jobs:
  code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Cache Bazel and pip
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/bazel
            ~/.cache/pip
          key: v2 # Not really needed, as bazel will sort out whatever it needs

      - name: Setup Bazel with cache
        uses: bazel-contrib/setup-bazel@0.15.0
        with:
          disk-cache: true
          repository-cache: true
          bazelisk-cache: true

      - name: Run test targets
        run: |
          bazel run //src:ide_support
          ./run_all_tests.sh
